spring:
  datasource:
    password: zhuzz2010
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
  thymeleaf:
    cache: false
  redis:
    host: 127.0.0.1
    port: 6379
    #Redis数据库索引（默认为0）
    database: 0
    jedis:
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 50
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 3000
        #连接池中的最大空闲连接
        max-idle: 20
        #连接池中的最小空闲连接
        min-idle: 2
    #连接超时时间（毫秒）
    timeout: 5000
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
